//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RR_System_MP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_Cancellation
    {
        public decimal Cancellation_Id { get; set; }
        public decimal Ticket_no { get; set; }
        public string C_status { get; set; }
        public decimal Train_id { get; set; }
        public Nullable<int> refundAmt { get; set; }
    
        public virtual Ticket_Booking Ticket_Booking { get; set; }
        public virtual Traindetail Traindetail { get; set; }
    }
}
