//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RR_System_MP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traindetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Traindetail()
        {
            this.Ticket_Booking = new HashSet<Ticket_Booking>();
            this.Class_price = new HashSet<Class_price>();
            this.Seat_available = new HashSet<Seat_available>();
            this.Ticket_Cancellation = new HashSet<Ticket_Cancellation>();
        }
    
        public decimal Train_id { get; set; }
        public string Train_name { get; set; }
        public string City_of_Departure { get; set; }
        public string city_of_Arrival { get; set; }
        public bool Status_of_Train { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket_Booking> Ticket_Booking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Class_price> Class_price { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seat_available> Seat_available { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket_Cancellation> Ticket_Cancellation { get; set; }
    }
}
