//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RR_System_MP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Userdetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Userdetail()
        {
            this.Ticket_Booking = new HashSet<Ticket_Booking>();
        }
    
        public int S_no { get; set; }
        public string userID { get; set; }
        public string userPassword { get; set; }
        public string userEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket_Booking> Ticket_Booking { get; set; }
    }
}
